"""add_lng_lat

Revision ID: 05d24a13f0fc
Revises: ef12275e8f8f
Create Date: 2023-03-31 04:33:33.823422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d24a13f0fc'
down_revision = 'ef12275e8f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng_lat', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lng_lat')

    # ### end Alembic commands ###
