"""Added device_id field to User model

Revision ID: 554177d0a8ed
Revises: cf1e472deff2
Create Date: 2025-02-22 22:45:24.234100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554177d0a8ed'
down_revision = 'cf1e472deff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['device_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
