"""Email activation.

Revision ID: 7a96bc60a027
Revises: 8d6a665ab523
Create Date: 2023-02-10 02:32:57.475659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a96bc60a027'
down_revision = '8d6a665ab523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('activated_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activated_on')
        batch_op.drop_column('activated')

    # ### end Alembic commands ###
