"""Initial migration.

Revision ID: a83359c97b49
Revises: 
Create Date: 2022-12-29 13:49:45.398808

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.models.user import ListType


# revision identifiers, used by Alembic.
revision = 'a83359c97b49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domaincheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belongs_to', sqlalchemy_utils.types.choice.ChoiceType(ListType), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('authority_token', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_num', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('discoverable', sa.Boolean(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domaincheck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('domaincheck')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
