"""add_lat_lng

Revision ID: c75c565e0a44
Revises: ef12275e8f8f
Create Date: 2023-04-01 06:06:22.833387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75c565e0a44'
down_revision = 'ef12275e8f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat_lng', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lat_lng')

    # ### end Alembic commands ###
