"""API Keys

Revision ID: cf1e472deff2
Revises: c75c565e0a44
Create Date: 2023-05-03 01:38:18.913101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1e472deff2'
down_revision = 'c75c565e0a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('client_secret', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('client_secret')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
